export const GET_LIST_USER_SUCCESS = 'GET_LIST_USER_SUCCESS';
export const GET_LIST_USER_ERROR = 'GET_LIST_USER_ERROR';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const USER_BY_ID_SUCCESS = 'USER_BY_ID_SUCCESS';
export const USER_BY_ID_ERROR = 'USER_BY_ID_ERROR';

export const USER_SUCCESS = 'USER_SUCESS';
export const USER_ERROR = 'USER_ERROR';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const MOVIES_SUCCESS = 'MOVIES_SUCCESS';
export const FILTER_MOVIES_SUCCESS = 'FILTER_MOVIES_SUCCESS';
export const PAGINATION_NUMBER = 'PAGINATION_NUMBER';
export const MOVIES_ERROR = 'MOVIES_ERROR';
export const SEASON_SUCCESS = 'SEASON_SUCCESS';



