export const MOVIES_SUCCESS = 'MOVIES_SUCCESS';
export const FILTER_MOVIES_SUCCESS = 'FILTER_MOVIES_SUCCESS';
export const LIST_CREDITS_SUCCESS = 'LIST_CREDITS_SUCCESS';
export const PAGINATION_NUMBER = 'PAGINATION_NUMBER';
export const MOVIES_ERROR = 'MOVIES_ERROR';
export const SEASON_SUCCESS = 'SEASON_SUCCESS';
export const SEASON_EPISODES_SUCCESS = 'SEASON_EPISODES_SUCCESS';




